name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            # first we need to setup our virtual environment before we build our pipeline
            - uses: actions/checkout@v6   # fetches code from our repository
            - uses: actions/setup-node@v6 # install node 
              with:
                node-version: '24'
            # lastly we need to install our app dependencies on the environment
            - name: install dependencies  
              run: npm install
            # now that the environment has been setup, we can run all scripts from package.json like we could on our own machine
            - name: Check style
              run: npm run eslint
            # next up is a step to run tests
            - name: Run npm tests
              run: npm run test
            # lastly build the prod version of our app
    Deploy_to_render:
        needs: [simple_deployment_pipeline]
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-latest
        steps:
            - run: curl ${{ secrets.RENDER_DEPLOY_HOOK}}
    tag_release:
        needs: [simple_deployment_pipeline]
        if : ${{ github.event_name == 'push'}}
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v6
              with:
                fetch-depth: 0
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.75.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: patch
